---
- name: Install gpg
  package:
    name: gpg
    state: present

- name: Add Jellyfin repo key
  apt_key:
    url: https://repo.jellyfin.org/ubuntu/jellyfin_team.gpg.key
    id: "{{ jellyfin_ubuntu_repo_key_id }}"
    state: present

- name: Add Jellyfin repo
  apt_repository:
    repo: "deb [arch=amd64] https://repo.jellyfin.org/ubuntu bionic main"
    filename: jellyfin
    state: present

- name: Install Jellyfin
  package:
    name: jellyfin
    state: present
  notify: Restart Jellyfin
